"""
Regenerate data/route_samples.json from the running game.

    uv run python tools/dump_route.py

The route is the level's authored path, sampled every `--spacing` units of arc.
Everything else measures position against it: it is the ruler that turns an
(x, y) into a single number, so reward can be a gradient instead of 38 sparse
goals.

It is not in the repository -- it is data read out of the game -- so this
rebuilds it. The checkpoint ladder is a different matter: that is hand-placed
and cannot be regenerated by any script. Keep your own backup of it.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "goi"))

from bridge import Bridge, DATA  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--spacing", type=float, default=0.25,
                    help="units of arc between samples; smaller is denser")
    ap.add_argument("--out", default=os.path.join(DATA, "route_samples.json"))
    args = ap.parse_args()

    c = Bridge()
    try:
        # splineinfo -> "length=1026.53 start=... end=..."
        info = dict(kv.split("=", 1) for kv in c.cmd("splineinfo").split())
        length = float(info["length"])
        # Sample by count rather than by distance: the plugin spaces n points
        # evenly along the arc, so the spacing comes out exact.
        n = max(2, int(length / args.spacing) + 1)
        recs = c.cmd(f"splinesample {n}").split(";")
        pts = [[float(v) for v in r.split(",")] for r in recs]
    finally:
        c.close()

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        json.dump(pts, f)
    print(f"  {len(pts)} samples, arc {pts[0][0]:.1f} -> {pts[-1][0]:.1f}")
    print(f"  -> {args.out}")


if __name__ == "__main__":
    main()
